name: Release

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
  workflow_dispatch: { }
  repository_dispatch:
    types: [release-created]

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate a1 deck
        run: python src/generate.py --mode per-level --level a1

      - name: Generate a2 deck
        run: python src/generate.py --mode per-level --level a2

      - name: Generate basic deck
        run: python src/generate.py --mode per-level --level basic

      - name: Check output folder contents
        run: ls -lh src/output/

      - name: Upload .apkg files
        uses: softprops/action-gh-release@v2
        with:
          files: src/output/*.apkg
