name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: italian-anki
          version-file: "VERSION"
          default-branch: main
          release-as: ""
          include-v-in-tag: true
          draft: false
          changelog-types: |
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"feature","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"docs","section":"Documentation","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":true},
              {"type":"refactor","section":"Code Refactoring","hidden":false},
              {"type":"test","section":"Tests","hidden":true},
              {"type":"build","section":"Build System","hidden":true},
              {"type":"ci","section":"Continuous Integration","hidden":true}
            ]

      # Trigger the release workflow when a release is created
      - name: Trigger release workflow
        if: ${{ steps.release.outputs.release_created }}
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: release-created
          client-payload: '{"tag_name": "${{ steps.release.outputs.tag_name }}"}'
          token: ${{ secrets.GITHUB_TOKEN }}
