name: Validate Conventional Commits

on:
  pull_request:
    branches:
      - main

jobs:
  conventional-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Validate Conventional Commits
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            feature
            fix
            docs
            chore
            refactor
            build
            ci
            test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

