name: Validate Decks

on:
  push:
    paths: ["decks/**/*.json", "generate.py", "validate.py", "deck.schema.json"]
  pull_request:
    paths: ["decks/**/*.json", "generate.py", "validate.py", "deck.schema.json"]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Validate decks
        run: python validate.py

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q
