name: Validate Anki Decks

on:
  push:
    paths: ["decks/**/*.json", "generate.py"]
  pull_request:
    paths: ["decks/**/*.json", "generate.py"]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install genanki

      - name: Validate JSON format
        run: |
          for f in decks/**/*.json; do
            echo "Validating $f"
            python -m json.tool < "$f" > /dev/null
          done

      - name: Build all decks
        run: python generate.py --all

      - name: Upload all .apkg files
        uses: actions/upload-artifact@v4
        with:
          name: anki-decks
          path: output/*.apkg
